### ISSUE TITLE
Limitation: Multiple entries of the same type

### ISSUE THREAD

**Issue by pgassmann** [markuman/hetzner_dns#4]
This module currently cannot manage multiple records of the same type.

a zone can have multiple A records for the same subdomain. Same is with AAAA and TXT records
Currently the module seems to update the first record (by id) that matches domain, record and type.

I don't know how this can be handled properly in an ansible module. would need to compare to other dns modules. It's also dependent on the features of the api.

**Comment by markuman** [comment]
I think it is possible. But not in different tasks. Because when a new tasks is executed and a new value for an existing A record is requested, it looks like you want to update the existing record.

```yml
        - name: add record
          markuman.hetzner_dns.record:
            zone_name: osuv.de
            name: some_cname
            value:
              - 8.8.8.8
              - 1.1.1.1
            type: A
            ttl: 300
          register: RECORD
```

That would be nice. But it will break the syntax compatibility. Until now, `value` is `type='str'`.  

Another solution would be a new parameter `append:` with `default: False`

```yml
        - name: append a record
          markuman.hetzner_dns.record:
            zone_name: osuv.de
            name: some_cname
            value: 1.1.1.1
            append: yes
            type: A
            ttl: 300
          register: RECORD
```

What do you think?

**Comment by pgassmann** [comment]
for A records, an array of values makes sense. thats also how the new gandi_livedns module works.

other dns modules have a parameter `solo:` which means exclusive.

* https://docs.ansible.com/ansible/devel/collections/community/general/gandi_livedns_module.html#ansible-collections-community-general-gandi-livedns-module
* https://docs.ansible.com/ansible/devel/collections/community/general/dnsimple_module.html#ansible-collections-community-general-dnsimple-module
* https://docs.ansible.com/ansible/devel/collections/community/general/netcup_dns_module.html#ansible-collections-community-general-netcup-dns-module

it would be nice to have a filter option to select records that should be replaced. for TXT records like spf a regex would be useful.

just an idea. perhaps naming can be better. (replace/regex/append)

~~~yaml
    - name: add multiple A records
      markuman.hetzner_dns.record:
        zone_name: example.it
        name: "@"
        solo: true
        type: A
        value:
          - 127.0.0.1
          - 127.0.0.2
        ttl: 300

    - name: manage spf record. replaces records beginning with regex
      markuman.hetzner_dns.record:
        zone_name: example.it
        name: "@"
        solo: True
        filter:
          - value: "^v=spf1"
        type: TXT
        value: "v=spf1 include:spf.protection.outlook.com include:spf.emailsignatures365.com ~all"
        ttl: 300

    - name: add a google site verification record
      markuman.hetzner_dns.record:
        zone_name: example.it
        name: "@"
        solo: False
        type: TXT
        value: "google-site-verification=asdfasdfasdf"
        ttl: 300

~~~

with `replace` parameter , which can be `True`, `False` or `Regex-String` for Value
True = replace all that match name and type
False = append if not existing with that value
string = replace records where the current value matches this regex

~~~yaml
    - name: add multiple A records
      markuman.hetzner_dns.record:
        zone_name: example.it
        name: "@"
        type: A
        replace: True
        value:
          - 127.0.0.1
          - 127.0.0.2
        ttl: 300

    - name: manage spf record
      markuman.hetzner_dns.record:
        zone_name: example.it
        name: "@"
        type: TXT
        replace: "^v=spf1"
        value: "v=spf1 include:spf.protection.outlook.com include:spf.emailsignatures365.com ~all"
        ttl: 300

    - name: add site verification record
      markuman.hetzner_dns.record:
        zone_name: example.it
        name: "@"
        type: TXT
        replace: False
        value: "google-site-verification=asdfasdfasdf"
        ttl: 300
~~~

The diff should show all matching records from before and the new records.

**Comment by markuman** [comment]
Interesting. in community.aws.route53 it's `overwrite:` parameter.  
The linked gandhi livedns has no `solo:` parameter. But it  is using value**s** with `type=list` parameter.  
While netcup and dnssimple module uses also `value` as `type=string` parameter.

That would be a way to keep barckward compatibility.
* `value` with `type=str` (current implementation).
* `values` with `type=list`  

So `value` and `values`would become `required_one_of`.  

I think I will support all three parameters (`solo`, `overwrite` and `replace` (_as alias_). Then everyone should feel comfortable.

```yml
- name: add site verification record
      markuman.hetzner_dns.record:
        zone_name: example.it
        name: "@"
        type: TXT
        replace: False
        value: "google-site-verification=asdfasdfasdf"
        ttl: 300

- name: add multiple A records
      markuman.hetzner_dns.record:
        zone_name: example.it
        name: "@"
        solo: true
        type: A
        values:
          - 127.0.0.1
          - 127.0.0.2
        ttl: 300

- name: add another A record
      markuman.hetzner_dns.record:
        zone_name: example.it
        name: "@"
        overwrite: no
        type: A
        value: 127.0.0.3
        ttl: 300
```

This will require to expand the integrationtest a lot, to make sure not to kill previous behaviour.  
The introduction of `values` and the overwrite alias paramter will result in 2.0.0 release. And it will took more time than one evening.  
I will first improve error messages and diff handling with release 1.3.0

**Comment by pgassmann** [comment]
i like the aliases and the value and values options.

what do you think about the regex matching? how would you handle different TXT entries? e.g. update the SPF record when the following entries are present:

```
@		IN	TXT	"v=spf1 include:spf.protection.outlook.com include:spf.emailsignatures365.com ~all"
@		IN	TXT	google-site-verification=bcdefasdfasdf
@		IN	TXT	google-site-verification=ccdefasdfasdf
```

what would `replace: true` do if multiple values are already present?

```yaml
- name: add site verification record
      markuman.hetzner_dns.record:
        zone_name: example.it
        name: "@"
        type: TXT
        replace: True
        value: "foo=asdfasdfasdf"
        ttl: 300
```

**Comment by markuman** [comment]
> i like the aliases and the value and values options.
> 
> what do you think about the regex matching? 

In  `2.0.0` I will priorise setting multple values per record.  
In `2.1.0` I will take a look at regexp handling. I haven't thought much about it yet. 

> how would you handle different TXT entries? e.g. update the SPF record when the following entries are present:
> 
> ```
> @		IN	TXT	"v=spf1 include:spf.protection.outlook.com include:spf.emailsignatures365.com ~all"
> @		IN	TXT	google-site-verification=bcdefasdfasdf
> @		IN	TXT	google-site-verification=ccdefasdfasdf
> ```
> 
> what would `replace: true` do if multiple values are already present?
> 
> ```yaml
> - name: add site verification record
>       markuman.hetzner_dns.record:
>         zone_name: example.it
>         name: "@"
>         type: TXT
>         replace: True
>         value: "foo=asdfasdfasdf"
>         ttl: 300
> ```

In my understanding, `replace: True` will replace all existing entries.  
In your example, when 3 entries exists, and a new one with `value: "string"` and `replace: True` is requested, the existing 3 will be purged and the new will be created.

Same will happen when you request 2 entries with `values: [...]` and `replace: True`.  
The existing 3 will be purged and replaced with the 2 requested.

When `replace: False` is requested, `value: "string"` or `values: [...]` will be append to the existing entries.

**Comment by markuman** [comment]
I decided to first release 1.4.0 that support adding multiple records of the same name just with existing `value:` parameter and the new alias parameter.  
Please take a look at the release notes: https://github.com/markuman/hetzner_dns/releases/tag/1.4.0

That is easier to take care not to break backwards compatibility with `1.x.x`.  
The other fancy stuff will result in 2.0.0.

**Comment by pgassmann** [comment]
The default `purge=True` does not work!  even without `purge: False`, it creates additional records!

This is "dangerous" if someone is using the newest version of your module! it keeps the previous entry.

```yaml
    - name: manage record website1
      markuman.hetzner_dns.record:
        zone_name: example.me
        name: website1
        type: A
        value: 127.0.0.1
        api_token: '{{ hetzner_dns_api_token }}'

    - name: manage record website1
      markuman.hetzner_dns.record:
        zone_name: example.me
        name: website1
        type: A
        value: 127.0.0.2
        api_token: '{{ hetzner_dns_api_token }}'
```

**Comment by pgassmann** [comment]
even with explicit purge: True, it does not remove other entries of the same name and type

**Comment by markuman** [comment]
> This is "dangerous" if someone is using the newest version of your module!

Living on the edge :) That's the price of a one-man-module. Basically there must be an official `community.hetzner` collection.

I guess I've fixed it - and also expand my integrationt test. `purge: True` was not explicit covered. https://github.com/markuman/hetzner_dns/commit/c57e5fd8b9a2a9ad8a9a3769a1f98e9664e0e685  
Can you checkout the main branch and test if it works for you?

**Comment by pgassmann** [comment]
Thank you for the update. it is closer, but it does not yet work as expected.

It now outputs a diff, but the other records are not removed. The diff does not match format. before is a list of records, and after is a dict of the should be record.

```
TASK [manage record website1] ********************************************************************************************************************************************************************************************************************************************************************
--- before
+++ after
@@ -1,20 +1,8 @@
-- name: website1
-  ttl: 300
-  type: A
-  value: 188.1.185.222
-  zone_id: Q6Xw7beZscUW3VMjYt7375
-- name: website1
-  ttl: 300
-  type: A
-  value: 188.1.185.223
-  zone_id: Q6Xw7beZscUW3VMjYt7375
-- name: website1
-  ttl: 300
-  type: A
-  value: 127.0.0.1
-  zone_id: Q6Xw7beZscUW3VMjYt7375
-- name: website1
-  ttl: 300
-  type: A
-  value: 127.0.0.2
-  zone_id: Q6Xw7beZscUW3VMjYt7375
+created: 2021-04-21 15:11:16.334 +0000 UTC
+id: c10395bc5ec4dfb6d90c6966ec512198
+modified: 2021-04-22 09:33:56.496 +0000 UTC
+name: website1
+ttl: 300
+type: A
+value: 127.0.0.2
+zone_id: Q6Xw7beZscUW3VMjYt7375

changed: [localhost]
```

**Comment by pgassmann** [comment]
it does update the last matching record if its different, but it does not remove the others.

if the record already exists, the console receives an update for 1 record, but no actual change.

**Comment by pgassmann** [comment]
so it works if you only have one record that matches, but not if there are already more than 1.

with 1 record, the diff before/after still does not match format.

**Comment by markuman** [comment]
> The diff does not match format. before is a list of records, and after is a dict of the should be record.

Because you can currently only request a single record (dict). And when you replace multiple records with a single record ... what do you expect? Should the requested single record also become a list?

> it does update the last matching record if its different, but it does not remove the others.

Ok, got it. It's fixed now and also covered by my integration test.

**Comment by pgassmann** [comment]
> Because you can currently only request a single record (dict). And when you replace multiple records with a single record ... what do you expect? Should the requested single record also become a list?

yes, if it can contain multiple records on one side it needs to be a list on the other side too. then the diff can show the difference. for a single record this should always work

for multple records:
if purge=True this would then be correct, as the other matching records are deleted.
if purge=False, the after should also contain the untouched records.

the fields created, id, modified and zone_id should not be in the diff.

**Comment by pgassmann** [comment]
@markuman How are things going? I think it would good to fix or otherwise revert the changes for the released version on galaxy, so that existing records can be updated as expected and not appended.

**Comment by markuman** [comment]
Huh? It is already fixed and updated I think. Release 1.4.3   (not included diff format fix)   
Is it still not working for you?

**Comment by pgassmann** [comment]
oh, sorry, I did not check the releases. Just looked at our conversation here.

**Comment by markuman** [comment]
this collection is EOL now, since community.dns is released with hetzner dns support.  
1.7.0 of markuman.hetzner_dns is released with deprecation warnings.
